// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MuseoMineralogia.Data;

#nullable disable

namespace MuseoMineralogia.Migrations
{
    [DbContext(typeof(MuseoContext))]
    partial class MuseoContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.14")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("MuseoMineralogia.Models.Carrello", b =>
                {
                    b.Property<int>("CarrelloId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CarrelloId"));

                    b.Property<int>("UtenteId")
                        .HasColumnType("int");

                    b.HasKey("CarrelloId");

                    b.HasIndex("UtenteId")
                        .IsUnique();

                    b.ToTable("Carrelli");
                });

            modelBuilder.Entity("MuseoMineralogia.Models.DettaglioOrdine", b =>
                {
                    b.Property<int>("DettaglioOrdineId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DettaglioOrdineId"));

                    b.Property<int>("OrdineId")
                        .HasColumnType("int");

                    b.Property<decimal>("PrezzoUnitario")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)");

                    b.Property<int>("Quantita")
                        .HasColumnType("int");

                    b.Property<int>("TipoBigliettoId")
                        .HasColumnType("int");

                    b.HasKey("DettaglioOrdineId");

                    b.HasIndex("OrdineId");

                    b.HasIndex("TipoBigliettoId");

                    b.ToTable("DettagliOrdine");
                });

            modelBuilder.Entity("MuseoMineralogia.Models.ElementoCarrello", b =>
                {
                    b.Property<int>("ElementoCarrelloId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ElementoCarrelloId"));

                    b.Property<int>("CarrelloId")
                        .HasColumnType("int");

                    b.Property<int>("Quantita")
                        .HasColumnType("int");

                    b.Property<int>("TipoBigliettoId")
                        .HasColumnType("int");

                    b.HasKey("ElementoCarrelloId");

                    b.HasIndex("CarrelloId");

                    b.HasIndex("TipoBigliettoId");

                    b.ToTable("ElementiCarrello");
                });

            modelBuilder.Entity("MuseoMineralogia.Models.Ordine", b =>
                {
                    b.Property<int>("OrdineId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("OrdineId"));

                    b.Property<DateTime>("DataOrdine")
                        .HasColumnType("datetime2");

                    b.Property<string>("Stato")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("UtenteId")
                        .HasColumnType("int");

                    b.HasKey("OrdineId");

                    b.HasIndex("UtenteId");

                    b.ToTable("Ordini");
                });

            modelBuilder.Entity("MuseoMineralogia.Models.TipoBiglietto", b =>
                {
                    b.Property<int>("TipoBigliettoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TipoBigliettoId"));

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<decimal>("Prezzo")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)");

                    b.HasKey("TipoBigliettoId");

                    b.ToTable("TipiBiglietto");

                    b.HasData(
                        new
                        {
                            TipoBigliettoId = 1,
                            Nome = "Intero",
                            Prezzo = 10.00m
                        },
                        new
                        {
                            TipoBigliettoId = 2,
                            Nome = "Ridotto (fino a 15 anni)",
                            Prezzo = 8.00m
                        });
                });

            modelBuilder.Entity("MuseoMineralogia.Models.Utente", b =>
                {
                    b.Property<int>("UtenteId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UtenteId"));

                    b.Property<string>("Cognome")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Nome")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("UtenteId");

                    b.ToTable("Utenti");
                });

            modelBuilder.Entity("MuseoMineralogia.Models.Carrello", b =>
                {
                    b.HasOne("MuseoMineralogia.Models.Utente", "Utente")
                        .WithOne("Carrello")
                        .HasForeignKey("MuseoMineralogia.Models.Carrello", "UtenteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Utente");
                });

            modelBuilder.Entity("MuseoMineralogia.Models.DettaglioOrdine", b =>
                {
                    b.HasOne("MuseoMineralogia.Models.Ordine", "Ordine")
                        .WithMany("DettagliOrdine")
                        .HasForeignKey("OrdineId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MuseoMineralogia.Models.TipoBiglietto", "TipoBiglietto")
                        .WithMany()
                        .HasForeignKey("TipoBigliettoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Ordine");

                    b.Navigation("TipoBiglietto");
                });

            modelBuilder.Entity("MuseoMineralogia.Models.ElementoCarrello", b =>
                {
                    b.HasOne("MuseoMineralogia.Models.Carrello", "Carrello")
                        .WithMany("ElementiCarrello")
                        .HasForeignKey("CarrelloId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MuseoMineralogia.Models.TipoBiglietto", "TipoBiglietto")
                        .WithMany()
                        .HasForeignKey("TipoBigliettoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Carrello");

                    b.Navigation("TipoBiglietto");
                });

            modelBuilder.Entity("MuseoMineralogia.Models.Ordine", b =>
                {
                    b.HasOne("MuseoMineralogia.Models.Utente", "Utente")
                        .WithMany("Ordini")
                        .HasForeignKey("UtenteId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Utente");
                });

            modelBuilder.Entity("MuseoMineralogia.Models.Carrello", b =>
                {
                    b.Navigation("ElementiCarrello");
                });

            modelBuilder.Entity("MuseoMineralogia.Models.Ordine", b =>
                {
                    b.Navigation("DettagliOrdine");
                });

            modelBuilder.Entity("MuseoMineralogia.Models.Utente", b =>
                {
                    b.Navigation("Carrello");

                    b.Navigation("Ordini");
                });
#pragma warning restore 612, 618
        }
    }
}
